### ISSUE TITLE
Item headline issue

### ISSUE THREAD

**Issue by dauphine-dev** [dauphine-dev/drop-feeds#44]
The parsing of headlines for the feed item list seems to have problems sometimes, currently visible with todays DailyWTF entry: http://thedailywtf.com/rss.aspx

**Comment by jinkama-san** [comment]
Here is the screenshot you requested. The problem seems to happen relatively often when the article contains embedded source code. [http://feeds.feedburner.com/ContinuousBlog](url) would be another example, but is an Atom-feed which might not be fully supported yet if I understand the road map correctly.

![drop-feeds-parse-1](https://user-images.githubusercontent.com/1462162/42021487-0225f0e0-7abb-11e8-9592-305c7ea35b72.PNG)

**Comment by jinkama-san** [comment]
Looking at some examples of this problem it occured to me that it is often (always?) related to embedded greater signs (>). So it maybe simply an escaping problem.
When I use Firefox view-source on the feed, the > seem to be properly encoded as \&gt; though.

**Comment by dauphine-dev** [comment]
@jinkama-san 
Do you have an example for today ?

**Comment by jinkama-san** [comment]
[http://thedailywtf.com/rss.aspx](url) shows the problem today on the first, third and fifth entry (usually only one entry per day is added, so this feed will show the problems for the next 2 weeks).
The original example today is the fifth (soon sixth) entry and has these 2 lines:

```
select_total_cost = select sum(cost_payable - amount_paid) from transaction_table where username = ? and cost_payable > amount_paid
select_time_penalty = select time_penalty from diagnostic_table where sem_id = ?
```

What is show as the headline in DropFeeds is the text after the '>'.

**Comment by dauphine-dev** [comment]
Arg, it works well for me.
What is your OS, you locale setting, the theme you are using, and any informations you can think that can have an impact on this... thx

**Comment by jinkama-san** [comment]
Windows7 64bit, German locale, Firefox 61 64bit (de) with theme "One Piece - Luffy and Sunny" (switching to the "Standard" theme didn't change anything though). And DropFeeds 0.7.13. Maybe you already fixed it in 0.8?

**Comment by dauphine-dev** [comment]
lol Y E S, you are right, It is already fixed (probably a side effect from an other fix) in 0.8
Thank you

0.8 is almost ready, it will come soon...

**Comment by jinkama-san** [comment]
I quickly tried the "Firefox Developer Edition" with a checkout from the current 0.8-branch and can confirm this. All feeds that had problems before are fine now. All other problems I mentioned seem to be fixed too. Thanks a lot! Only a "Donate" button is still missing ;-).

**Comment by dauphine-dev** [comment]
Yeah I have thought to a "Donate" button, it will come day... ;-)
